import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type Language = 'en' | 'it';

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.dashboard': 'Dashboard',
    'nav.submissions': 'Submissions',
    'nav.organizations': 'Organizations',
    'nav.users': 'Users',
    'nav.newSubmission': 'New Submission',
    'nav.mySubmissions': 'My Submissions',
    'nav.profile': 'Profile',
    'nav.navigation': 'Navigation',
    'nav.commandCenter': 'Command Center',
    'nav.supplierPortal': 'Supplier Portal',
    // Auth
    'auth.welcomeBack': 'Welcome back',
    'auth.createAccount': 'Create account',
    'auth.signIn': 'Sign In',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.createOne': 'Create one',
    'auth.signInLink': 'Sign in',
    'auth.orContinue': 'Or continue with',
    'auth.selectRole': 'Select your role and create an account',
    'auth.signInContinue': 'Sign in to continue',
    'auth.supplier': 'Supplier',
    'auth.manager': 'ESG Manager',
    'auth.supplierDesc': 'Submit energy data & upload invoices',
    'auth.managerDesc': 'Review submissions & approve data',
    // Wizard
    'wizard.howSubmit': 'How would you like to submit?',
    'wizard.chooseMethod': 'Choose manual entry or let our AI extract data from your invoices',
    'wizard.manualEntry': 'Manual Entry',
    'wizard.manualDesc': 'Type in your electricity, gas, fuel, and waste consumption values directly',
    'wizard.smartUpload': 'Smart Upload',
    'wizard.smartDesc': 'Upload an invoice or bill and our AI will automatically extract the energy data',
    'wizard.recommended': 'Recommended',
    'wizard.getStarted': 'Get started',
    'wizard.uploadDoc': 'Upload document',
    'wizard.stepMethod': 'Choose Method',
    'wizard.stepMethodDesc': 'Manual or AI',
    'wizard.stepData': 'Enter Data',
    'wizard.stepDataDesc': 'Provide details',
    'wizard.stepReview': 'Review',
    'wizard.stepReviewDesc': 'Submit data',
    // Common
    'common.logout': 'Logout',
    'common.approve': 'Approve',
    'common.requestRevision': 'Request Revision',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.saving': 'Saving…',
    'common.saveChanges': 'Save Changes',
    'common.create': 'Create',
    'common.creating': 'Creating...',
    'common.search': 'Search',
    'common.noData': 'No data yet',
    'common.unknown': 'Unknown',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.total': 'total',
    'common.returnHome': 'Return to Home',
    'common.pageNotFound': 'Oops! Page not found',
    // Branding
    'brand.title': 'Enterprise ESG Data Platform',
    'brand.subtitle': 'AI-powered data extraction with immutable audit trails. Compliance made simple for CSRD & EUDR regulations.',
    'brand.feature1': 'AI-Powered Document Extraction',
    'brand.feature2': 'Immutable Blockchain Audit Trail',
    'brand.feature3': 'CSRD & EUDR Compliance Ready',
    // Supplier Submit
    'submit.title': 'New Submission',
    'submit.subtitle': 'Submit your energy consumption data for ESG reporting',
    // Supplier History
    'history.title': 'My Submissions',
    'history.subtitle': 'Track the status of all your energy data submissions',
    'history.totalSubmissions': 'Total Submissions',
    'history.totalCO2e': 'Total CO₂e (tonnes)',
    'history.awaitingReview': 'Awaiting Review',
    'history.submissionHistory': 'Submission History',
    'history.noSubmissions': 'No submissions yet. Start by creating a new submission.',
    'history.statusPending': 'Pending',
    'history.statusApproved': 'Approved',
    'history.statusRejected': 'Rejected',
    'history.revisionFeedback': 'Manager Feedback',
    // Supplier Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account details',
    'profile.personalInfo': 'Personal Information',
    'profile.updateName': 'Update your display name',
    'profile.role': 'Role',
    'profile.profileUpdated': 'Profile updated',
    // Energy Data Form
    'energy.title': 'Energy Consumption Data',
    'energy.subtitle': 'Enter your monthly energy consumption values below',
    'energy.electricity': 'Electricity',
    'energy.naturalGas': 'Natural Gas',
    'energy.fuel': 'Fuel',
    'energy.waste': 'Waste',
    'energy.water': 'Water',
    'energy.continueReview': 'Continue to Review',
    'energy.leaveZero': '💡 Leave fields at 0 if not applicable',
    'energy.fixErrors': 'Please fix the errors before continuing',
    // Smart Upload
    'smart.aiPowered': 'AI-Powered',
    'smart.title': 'Smart Document Upload',
    'smart.subtitle': 'Upload your energy invoices and our AI will automatically extract the data',
    'smart.dragDrop': 'Drag & drop your invoice',
    'smart.dropHere': 'Drop your file here',
    'smart.orBrowse': 'or click to browse (PDF, PNG, JPG — max 4MB)',
    'smart.uploading': 'Uploading file...',
    'smart.scanning': 'Scanning document...',
    'smart.extracting': 'AI extracting energy data...',
    'smart.complete': 'Extraction complete!',
    'smart.processing': 'Processing document...',
    'smart.confidence': 'Confidence',
    'smart.failed': 'Extraction failed',
    'smart.failedHint': 'Try a different file or switch to manual entry',
    'smart.manualInstead': 'Enter data manually instead',
    'smart.fileTooLarge': 'File too large. Maximum 4MB for AI extraction.',
    'smart.pdfOrImage': 'Please upload a PDF or image file',
    'smart.errorInvalidDoc': 'This does not appear to be a utility bill or energy invoice. Please upload the correct document.',
    'smart.errorUnreadable': 'The document is too blurry or low-quality to read. Please upload a clearer photo or scan.',
    'smart.rateLimited': 'Too many requests. Please wait a moment and try again.',
    'smart.usageLimited': 'AI usage limit reached. Please try again later.',
    // Review & Submit
    'review.title': 'Review & Submit',
    'review.subtitle': 'Verify the extracted data below before submitting',
    'review.aiAutoFilled': 'AI Auto-filled',
    'review.carbonFootprint': 'Calculated Carbon Footprint',
    'review.emissionFactors': 'Based on standard emission factors for Scope 1 & 2 emissions',
    'review.submitting': 'Submitting...',
    'review.submitData': 'Submit Data',
    'review.success': 'Submission successful! Your data has been recorded.',
    // Submission Success
    'success.title': 'Submission Successful!',
    'success.subtitle': 'Your energy data has been securely recorded and is now awaiting review by your ESG manager.',
    'success.statusPending': 'Status: Pending Review',
    'success.notified': "You'll be notified once approved",
    'success.encrypted': '🔒 Data encrypted & stored securely',
    'success.auditTrail': '📋 Audit trail created',
    'success.newSubmission': 'New Submission',
    'success.viewSubmissions': 'View My Submissions',
    // Forgot Password
    'forgot.title': 'Reset your password',
    'forgot.subtitle': 'Enter your email to receive a reset link',
    'forgot.checkEmail': 'Check your email',
    'forgot.sentTo': "We've sent a password reset link to",
    'forgot.backToLogin': 'Back to login',
    'forgot.sending': 'Sending...',
    'forgot.sendLink': 'Send Reset Link',
    // Reset Password
    'reset.title': 'Set new password',
    'reset.subtitle': 'Choose a strong password for your account',
    'reset.newPassword': 'New Password',
    'reset.confirmPassword': 'Confirm Password',
    'reset.updating': 'Updating...',
    'reset.updatePassword': 'Update Password',
    'reset.loadingSession': 'Loading recovery session...',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Real-time ESG compliance overview',
    'dashboard.pendingReviews': 'Pending Reviews',
    'dashboard.complianceRate': 'Compliance Rate',
    'dashboard.totalEmissions': 'Total Emissions',
    'dashboard.activeSuppliers': 'Active Suppliers',
    'dashboard.emissionsBySource': 'Emissions by Source',
    'dashboard.statusDistribution': 'Status Distribution',
    'dashboard.recentSubmissions': 'Recent Submissions',
    'dashboard.noSubmissions': 'No submissions yet',
    'dashboard.pending': 'Pending',
    'dashboard.approved': 'Approved',
    'dashboard.rejected': 'Rejected',
    // Admin Submissions
    'adminSub.title': 'Submissions',
    'adminSub.subtitle': 'Review and manage supplier ESG submissions',
    'adminSub.searchSuppliers': 'Search suppliers...',
    'adminSub.allStatus': 'All Status',
    'adminSub.noSubmissions': 'No submissions found',
    'adminSub.review': 'Review',
    // Admin Review
    'adminReview.backToDashboard': 'Back to Dashboard',
    'adminReview.backToSubmissions': 'Back to Submissions',
    'adminReview.unknownSupplier': 'Unknown Supplier',
    'adminReview.pendingReview': 'Pending Review',
    'adminReview.approved': 'Approved',
    'adminReview.revisionRequested': 'Revision Requested',
    'adminReview.vsmeData': 'VSME Extracted Data',
    'adminReview.totalEmissions': 'Total Calculated Emissions',
    'adminReview.formula': 'Formula: Electricity × 0.5 + Gas × 2.0 + Fuel × 2.5 + Waste × 0.3',
    'adminReview.revisionNotes': 'Revision Notes',
    'adminReview.auditTrail': 'Audit Trail',
    'adminReview.submitted': 'Submitted',
    'adminReview.verified': 'Verified',
    'adminReview.auditHash': 'Immutable Audit Hash',
    'adminReview.evidence': 'Supporting Evidence',
    'adminReview.downloadOriginal': 'Download Original',
    'adminReview.noDocument': 'No document uploaded',
    'adminReview.noDocumentHint': 'The supplier did not attach a file to this submission',
    'adminReview.reviewComplete': 'Review complete? Choose an action below.',
    'adminReview.requestRevision': 'Request Revision',
    'adminReview.approveSubmission': 'Approve Submission',
    'adminReview.revisionReason': 'Provide a reason so the supplier knows what to correct before resubmitting.',
    'adminReview.revisionPlaceholder': 'e.g. Electricity figures seem too low for a facility of this size. Please double-check your utility bill and resubmit.',
    'adminReview.submitRevision': 'Submit Revision Request',
    'adminReview.loadingSubmission': 'Loading submission…',
    'adminReview.notFound': 'Submission not found',
    'adminReview.provideReason': 'Please provide a reason for revision.',
    'adminReview.approvedSuccess': 'Submission approved successfully.',
    'adminReview.revisionSuccess': 'Revision requested — supplier will be notified.',
    // Organizations
    'orgs.title': 'Organizations',
    'orgs.subtitle': 'Manage multi-tenant organizations',
    'orgs.newOrg': 'New Organization',
    'orgs.orgName': 'Organization Name',
    'orgs.placeholder': 'e.g. Acme Corporation',
    'orgs.createForGrouping': 'Create a new organization for supplier grouping',
    'orgs.noOrgs': 'No organizations yet. Create one to get started.',
    'orgs.created': 'Created',
    'orgs.enterName': 'Enter a name',
    'orgs.orgCreated': 'Organization created',
    // Users
    'users.title': 'Users',
    'users.subtitle': 'Manage users and assign organizations',
    'users.searchUsers': 'Search users...',
    'users.name': 'Name',
    'users.role': 'Role',
    'users.organization': 'Organization',
    'users.joined': 'Joined',
    'users.assignOrg': 'Assign Org',
    'users.assignOrgTitle': 'Assign Organization',
    'users.assignOrgDesc': 'Assign {name} to an organization',
    'users.selectOrg': 'Select organization',
    'users.noOrg': 'No Organization',
    'users.noUsers': 'No users found',
    'users.userUpdated': 'User updated',
    'users.users': 'users',
    // Audit Trail
    'audit.title': 'Audit Trail',
    'audit.subtitle': 'Immutable record of all submission actions',
    'audit.noLogs': 'No audit logs yet',
    // Onboarding
    'onboarding.step1Title': 'Welcome to ESG Chain',
    'onboarding.step1Desc': 'Your platform for streamlined ESG reporting and compliance. Submit energy data, track emissions, and stay audit-ready.',
    'onboarding.step2Title': 'Upload or Enter Data',
    'onboarding.step2Desc': 'Choose Smart Upload to let AI extract data from your utility bills, or enter values manually.',
    'onboarding.step3Title': 'Track Your Submissions',
    'onboarding.step3Desc': 'View all your submissions, check approval status, and respond to manager feedback from one dashboard.',
    'onboarding.step4Title': 'You\'re Ready!',
    'onboarding.step4Desc': 'Start by creating your first submission. Your ESG manager will review and approve your data.',
    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.getStarted': 'Get Started',
    // Energy extras
    'energy.periodStart': 'Period Start',
    'energy.periodEnd': 'Period End',
    'energy.period': 'Period',
    'energy.reportingPeriod': 'Reporting Period',
    // Admin extras
    'nav.auditTrail': 'Audit Trail',
    'adminSub.exportCSV': 'Export CSV',
    'adminSub.exported': 'CSV exported successfully',
    // Feedback
    'history.actionRequired': 'Action Required',
    'history.submissionNeedsRevision': 'submission needs revision',
    'history.submissionsNeedRevision': 'submissions need revision',
  },
  it: {
    // Nav
    'nav.dashboard': 'Pannello',
    'nav.submissions': 'Invii',
    'nav.organizations': 'Organizzazioni',
    'nav.users': 'Utenti',
    'nav.newSubmission': 'Nuovo Invio',
    'nav.mySubmissions': 'I Miei Invii',
    'nav.profile': 'Profilo',
    'nav.navigation': 'Navigazione',
    'nav.commandCenter': 'Centro di Comando',
    'nav.supplierPortal': 'Portale Fornitore',
    // Auth
    'auth.welcomeBack': 'Bentornato',
    'auth.createAccount': 'Crea account',
    'auth.signIn': 'Accedi',
    'auth.signingIn': 'Accesso in corso...',
    'auth.creatingAccount': 'Creazione account...',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Nome completo',
    'auth.forgotPassword': 'Hai dimenticato la password?',
    'auth.noAccount': 'Non hai un account?',
    'auth.hasAccount': 'Hai già un account?',
    'auth.createOne': 'Creane uno',
    'auth.signInLink': 'Accedi',
    'auth.orContinue': 'Oppure continua con',
    'auth.selectRole': 'Seleziona il tuo ruolo e crea un account',
    'auth.signInContinue': 'Accedi per continuare',
    'auth.supplier': 'Fornitore',
    'auth.manager': 'Manager ESG',
    'auth.supplierDesc': 'Invia dati energetici e carica fatture',
    'auth.managerDesc': 'Rivedi invii e approva dati',
    // Wizard
    'wizard.howSubmit': 'Come vuoi inviare i dati?',
    'wizard.chooseMethod': 'Scegli l\'inserimento manuale o lascia che la nostra IA estragga i dati dalle tue fatture',
    'wizard.manualEntry': 'Inserimento Manuale',
    'wizard.manualDesc': 'Inserisci i valori di elettricità, gas, carburante e rifiuti direttamente',
    'wizard.smartUpload': 'Caricamento Smart',
    'wizard.smartDesc': 'Carica una fattura e la nostra IA estrarrà automaticamente i dati energetici',
    'wizard.recommended': 'Consigliato',
    'wizard.getStarted': 'Inizia',
    'wizard.uploadDoc': 'Carica documento',
    'wizard.stepMethod': 'Scegli Metodo',
    'wizard.stepMethodDesc': 'Manuale o IA',
    'wizard.stepData': 'Inserisci Dati',
    'wizard.stepDataDesc': 'Fornisci dettagli',
    'wizard.stepReview': 'Revisione',
    'wizard.stepReviewDesc': 'Invia dati',
    // Common
    'common.logout': 'Esci',
    'common.approve': 'Approva',
    'common.requestRevision': 'Richiedi Revisione',
    'common.cancel': 'Annulla',
    'common.submit': 'Invia',
    'common.loading': 'Caricamento...',
    'common.back': 'Indietro',
    'common.save': 'Salva',
    'common.saving': 'Salvataggio…',
    'common.saveChanges': 'Salva Modifiche',
    'common.create': 'Crea',
    'common.creating': 'Creazione...',
    'common.search': 'Cerca',
    'common.noData': 'Nessun dato',
    'common.unknown': 'Sconosciuto',
    'common.date': 'Data',
    'common.status': 'Stato',
    'common.actions': 'Azioni',
    'common.total': 'totale',
    'common.returnHome': 'Torna alla Home',
    'common.pageNotFound': 'Oops! Pagina non trovata',
    // Branding
    'brand.title': 'Piattaforma Dati ESG Aziendale',
    'brand.subtitle': 'Estrazione dati con IA e tracciabilità immutabile. Conformità semplificata per CSRD e EUDR.',
    'brand.feature1': 'Estrazione Documenti con IA',
    'brand.feature2': 'Tracciabilità Blockchain Immutabile',
    'brand.feature3': 'Conformità CSRD e EUDR',
    // Supplier Submit
    'submit.title': 'Nuovo Invio',
    'submit.subtitle': 'Invia i tuoi dati di consumo energetico per il report ESG',
    // Supplier History
    'history.title': 'I Miei Invii',
    'history.subtitle': 'Monitora lo stato di tutti i tuoi invii di dati energetici',
    'history.totalSubmissions': 'Invii Totali',
    'history.totalCO2e': 'CO₂e Totale (tonnellate)',
    'history.awaitingReview': 'In Attesa di Revisione',
    'history.submissionHistory': 'Storico Invii',
    'history.noSubmissions': 'Nessun invio ancora. Inizia creando un nuovo invio.',
    'history.statusPending': 'In Attesa',
    'history.statusApproved': 'Approvato',
    'history.statusRejected': 'Rifiutato',
    'history.revisionFeedback': 'Feedback del Manager',
    // Supplier Profile
    'profile.title': 'Profilo',
    'profile.subtitle': 'Gestisci i dettagli del tuo account',
    'profile.personalInfo': 'Informazioni Personali',
    'profile.updateName': 'Aggiorna il tuo nome visualizzato',
    'profile.role': 'Ruolo',
    'profile.profileUpdated': 'Profilo aggiornato',
    // Energy Data Form
    'energy.title': 'Dati di Consumo Energetico',
    'energy.subtitle': 'Inserisci i tuoi valori mensili di consumo energetico',
    'energy.electricity': 'Elettricità',
    'energy.naturalGas': 'Gas Naturale',
    'energy.fuel': 'Carburante',
    'energy.waste': 'Rifiuti',
    'energy.water': 'Acqua',
    'energy.continueReview': 'Continua alla Revisione',
    'energy.leaveZero': '💡 Lascia i campi a 0 se non applicabile',
    'energy.fixErrors': 'Correggi gli errori prima di continuare',
    // Smart Upload
    'smart.aiPowered': 'Basato su IA',
    'smart.title': 'Caricamento Smart Documenti',
    'smart.subtitle': 'Carica le tue fatture energetiche e la nostra IA estrarrà automaticamente i dati',
    'smart.dragDrop': 'Trascina e rilascia la tua fattura',
    'smart.dropHere': 'Rilascia il file qui',
    'smart.orBrowse': 'o clicca per sfogliare (PDF, PNG, JPG — max 4MB)',
    'smart.uploading': 'Caricamento file...',
    'smart.scanning': 'Scansione documento...',
    'smart.extracting': 'IA in estrazione dati energetici...',
    'smart.complete': 'Estrazione completata!',
    'smart.processing': 'Elaborazione documento...',
    'smart.confidence': 'Affidabilità',
    'smart.failed': 'Estrazione fallita',
    'smart.failedHint': 'Prova un file diverso o passa all\'inserimento manuale',
    'smart.manualInstead': 'Inserisci i dati manualmente',
    'smart.fileTooLarge': 'File troppo grande. Massimo 4MB per l\'estrazione IA.',
    'smart.pdfOrImage': 'Carica un file PDF o immagine',
    'smart.errorInvalidDoc': 'Questo documento non sembra essere una bolletta o fattura energetica. Per favore carica il documento corretto.',
    'smart.errorUnreadable': 'Il documento è troppo sfocato o di bassa qualità per essere letto. Per favore carica una foto o scansione più nitida.',
    'smart.rateLimited': 'Troppe richieste. Attendi un momento e riprova.',
    'smart.usageLimited': 'Limite di utilizzo IA raggiunto. Riprova più tardi.',
    // Review & Submit
    'review.title': 'Revisione e Invio',
    'review.subtitle': 'Verifica i dati estratti prima di inviare',
    'review.aiAutoFilled': 'Compilato dall\'IA',
    'review.carbonFootprint': 'Impronta di Carbonio Calcolata',
    'review.emissionFactors': 'Basato su fattori di emissione standard per emissioni Scope 1 e 2',
    'review.submitting': 'Invio in corso...',
    'review.submitData': 'Invia Dati',
    'review.success': 'Invio riuscito! I tuoi dati sono stati registrati.',
    // Submission Success
    'success.title': 'Invio Riuscito!',
    'success.subtitle': 'I tuoi dati energetici sono stati registrati in modo sicuro e sono in attesa di revisione dal tuo manager ESG.',
    'success.statusPending': 'Stato: In Attesa di Revisione',
    'success.notified': 'Sarai notificato una volta approvato',
    'success.encrypted': '🔒 Dati crittografati e archiviati in modo sicuro',
    'success.auditTrail': '📋 Traccia di audit creata',
    'success.newSubmission': 'Nuovo Invio',
    'success.viewSubmissions': 'Vedi I Miei Invii',
    // Forgot Password
    'forgot.title': 'Reimposta la password',
    'forgot.subtitle': 'Inserisci la tua email per ricevere un link di reset',
    'forgot.checkEmail': 'Controlla la tua email',
    'forgot.sentTo': 'Abbiamo inviato un link di reset della password a',
    'forgot.backToLogin': 'Torna al login',
    'forgot.sending': 'Invio...',
    'forgot.sendLink': 'Invia Link di Reset',
    // Reset Password
    'reset.title': 'Imposta nuova password',
    'reset.subtitle': 'Scegli una password sicura per il tuo account',
    'reset.newPassword': 'Nuova Password',
    'reset.confirmPassword': 'Conferma Password',
    'reset.updating': 'Aggiornamento...',
    'reset.updatePassword': 'Aggiorna Password',
    'reset.loadingSession': 'Caricamento sessione di recupero...',
    // Dashboard
    'dashboard.title': 'Pannello',
    'dashboard.subtitle': 'Panoramica conformità ESG in tempo reale',
    'dashboard.pendingReviews': 'Revisioni in Attesa',
    'dashboard.complianceRate': 'Tasso di Conformità',
    'dashboard.totalEmissions': 'Emissioni Totali',
    'dashboard.activeSuppliers': 'Fornitori Attivi',
    'dashboard.emissionsBySource': 'Emissioni per Fonte',
    'dashboard.statusDistribution': 'Distribuzione Stato',
    'dashboard.recentSubmissions': 'Invii Recenti',
    'dashboard.noSubmissions': 'Nessun invio ancora',
    'dashboard.pending': 'In Attesa',
    'dashboard.approved': 'Approvato',
    'dashboard.rejected': 'Rifiutato',
    // Admin Submissions
    'adminSub.title': 'Invii',
    'adminSub.subtitle': 'Rivedi e gestisci gli invii ESG dei fornitori',
    'adminSub.searchSuppliers': 'Cerca fornitori...',
    'adminSub.allStatus': 'Tutti gli Stati',
    'adminSub.noSubmissions': 'Nessun invio trovato',
    'adminSub.review': 'Rivedi',
    // Admin Review
    'adminReview.backToDashboard': 'Torna al Pannello',
    'adminReview.backToSubmissions': 'Torna agli Invii',
    'adminReview.unknownSupplier': 'Fornitore Sconosciuto',
    'adminReview.pendingReview': 'In Attesa di Revisione',
    'adminReview.approved': 'Approvato',
    'adminReview.revisionRequested': 'Revisione Richiesta',
    'adminReview.vsmeData': 'Dati Estratti VSME',
    'adminReview.totalEmissions': 'Emissioni Totali Calcolate',
    'adminReview.formula': 'Formula: Elettricità × 0.5 + Gas × 2.0 + Carburante × 2.5 + Rifiuti × 0.3',
    'adminReview.revisionNotes': 'Note di Revisione',
    'adminReview.auditTrail': 'Traccia di Audit',
    'adminReview.submitted': 'Inviato',
    'adminReview.verified': 'Verificato',
    'adminReview.auditHash': 'Hash di Audit Immutabile',
    'adminReview.evidence': 'Documentazione di Supporto',
    'adminReview.downloadOriginal': 'Scarica Originale',
    'adminReview.noDocument': 'Nessun documento caricato',
    'adminReview.noDocumentHint': 'Il fornitore non ha allegato un file a questo invio',
    'adminReview.reviewComplete': 'Revisione completata? Scegli un\'azione qui sotto.',
    'adminReview.requestRevision': 'Richiedi Revisione',
    'adminReview.approveSubmission': 'Approva Invio',
    'adminReview.revisionReason': 'Fornisci un motivo così il fornitore saprà cosa correggere prima di reinviare.',
    'adminReview.revisionPlaceholder': 'es. I valori di elettricità sembrano troppo bassi per un impianto di queste dimensioni. Controlla la bolletta e reinvia.',
    'adminReview.submitRevision': 'Invia Richiesta di Revisione',
    'adminReview.loadingSubmission': 'Caricamento invio…',
    'adminReview.notFound': 'Invio non trovato',
    'adminReview.provideReason': 'Fornisci un motivo per la revisione.',
    'adminReview.approvedSuccess': 'Invio approvato con successo.',
    'adminReview.revisionSuccess': 'Revisione richiesta — il fornitore sarà notificato.',
    // Organizations
    'orgs.title': 'Organizzazioni',
    'orgs.subtitle': 'Gestisci organizzazioni multi-tenant',
    'orgs.newOrg': 'Nuova Organizzazione',
    'orgs.orgName': 'Nome Organizzazione',
    'orgs.placeholder': 'es. Acme Corporation',
    'orgs.createForGrouping': 'Crea una nuova organizzazione per raggruppare i fornitori',
    'orgs.noOrgs': 'Nessuna organizzazione ancora. Creane una per iniziare.',
    'orgs.created': 'Creata il',
    'orgs.enterName': 'Inserisci un nome',
    'orgs.orgCreated': 'Organizzazione creata',
    // Users
    'users.title': 'Utenti',
    'users.subtitle': 'Gestisci utenti e assegna organizzazioni',
    'users.searchUsers': 'Cerca utenti...',
    'users.name': 'Nome',
    'users.role': 'Ruolo',
    'users.organization': 'Organizzazione',
    'users.joined': 'Iscritto',
    'users.assignOrg': 'Assegna Org',
    'users.assignOrgTitle': 'Assegna Organizzazione',
    'users.assignOrgDesc': 'Assegna {name} a un\'organizzazione',
    'users.selectOrg': 'Seleziona organizzazione',
    'users.noOrg': 'Nessuna Organizzazione',
    'users.noUsers': 'Nessun utente trovato',
    'users.userUpdated': 'Utente aggiornato',
    'users.users': 'utenti',
    // Audit Trail
    'audit.title': 'Traccia di Audit',
    'audit.subtitle': 'Registro immutabile di tutte le azioni sugli invii',
    'audit.noLogs': 'Nessun log di audit ancora',
    // Onboarding
    'onboarding.step1Title': 'Benvenuto su ESG Chain',
    'onboarding.step1Desc': 'La tua piattaforma per report ESG semplificati e conformità. Invia dati energetici, monitora emissioni e resta pronto per gli audit.',
    'onboarding.step2Title': 'Carica o Inserisci Dati',
    'onboarding.step2Desc': 'Scegli Caricamento Smart per far estrarre i dati dall\'IA dalle tue bollette, o inserisci i valori manualmente.',
    'onboarding.step3Title': 'Monitora i Tuoi Invii',
    'onboarding.step3Desc': 'Visualizza tutti i tuoi invii, controlla lo stato di approvazione e rispondi al feedback del manager da un\'unica dashboard.',
    'onboarding.step4Title': 'Sei Pronto!',
    'onboarding.step4Desc': 'Inizia creando il tuo primo invio. Il tuo manager ESG revisionerà e approverà i tuoi dati.',
    'onboarding.skip': 'Salta',
    'onboarding.next': 'Avanti',
    'onboarding.getStarted': 'Inizia',
    // Energy extras
    'energy.periodStart': 'Inizio Periodo',
    'energy.periodEnd': 'Fine Periodo',
    'energy.period': 'Periodo',
    'energy.reportingPeriod': 'Periodo di Rendicontazione',
    // Admin extras
    'nav.auditTrail': 'Traccia di Audit',
    'adminSub.exportCSV': 'Esporta CSV',
    'adminSub.exported': 'CSV esportato con successo',
    // Feedback
    'history.actionRequired': 'Azione Richiesta',
    'history.submissionNeedsRevision': 'invio necessita revisione',
    'history.submissionsNeedRevision': 'invii necessitano revisione',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved === 'it' ? 'it' : 'en') as Language;
  });

  const handleSetLanguage = useCallback((lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app-language', lang);
  }, []);

  const t = useCallback((key: string, replacements?: Record<string, string>) => {
    let text = translations[language][key] ?? key;
    if (replacements) {
      Object.entries(replacements).forEach(([k, v]) => {
        text = text.replace(`{${k}}`, v);
      });
    }
    return text;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

const fallbackT = (key: string) => translations['en'][key] ?? key;
const fallbackContext: LanguageContextType = { language: 'en', setLanguage: () => {}, t: fallbackT };

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  return ctx ?? fallbackContext;
}
